### ISSUE TITLE
Assigning row and column in grids does not work

### ISSUE THREAD

**Issue by gbishop** [UNC-Project-Open-AAC/OS-DPI#7]
I broke Graham's changes.

We need to figure out how **pages** work with assigned positions.

**Comment by gbishop** [comment]
I see you throw an error is row or column are out of bounds. Our users shouldn't have to deal with that. We need to figure out the polite thing to do in that case. 

Possibilities include:

1. Increase grid size to accommodate or 
2. skip entries that don't fit.
3. others?

@lageist or @sofia-bg what should we do?

**Comment by gbishop** [comment]
We need to clean up the type complaints as well.

**Comment by gtrogdon** [comment]
I'm thinking option 1, potentially with a way to notify the user of the adaptation (although I suppose it doesn't matter too much one way or another if the dimensions are defined explicitly in layout, or if they are inferred from the content, at least in the case of using explicit row/col/page content entries). But definitely let me know if some other behavior would be preferable for y'all.

**Comment by gbishop** [comment]
I guess we could have an option on the grid to say whether we wanted to
clip or expand.

**Comment by gtrogdon** [comment]
For sure. I'll wait and see before adding anything.

Also, fixing the type complaints now. Not sure how I forgot to do that.

**Comment by gbishop** [comment]
The page controls are appearing outside the grid.

**Comment by gtrogdon** [comment]
above should be fixed now

**Comment by gbishop** [comment]
Go ahead and "clip" entries that are outside the specified bounds. I think all it will require is replacing that throw with a continue (or some such). If folks want more we can add it later. I think clipping makes sense.

**Comment by gbishop** [comment]
The paging control still appears in outside in some circumstances. What I'm seeing is a design that specifies rows and columns but the grid is too small. I don't think we should page those. Just drop them on the floor. If they wanted it paged they would have included a page field.

**Comment by gbishop** [comment]
I'm thinking @gtrogdon had the right idea with the automatic sizing of the grid when assigning rows and columns. I think we need to add a property to grid to specify whether we want to specify the size and let the items fill the grid as in my initial implementation or ignore the specified size (disable the controls) and explicitly place them with row and column from the content. 

If you choose explicit placement, entries without row, column and optional page are ignored. That would eliminate lots of strange edge cases. 

This would make don't care and first wins as in #42 much easier to implement.
